  exclude-dirs:
    - db
    - gen
    - tmp
    - docs
inters:
  enable:
  - errcheck
  - errorlint
  - gofmt
  - govet
  - staticcheck
  - gosimple
  - ineffassign
  - unused
  - gosec
  - bodyclose
  - gocyclo
  - gocognit
  - gocritic
  - godot
  - prealloc
  - revive
run:
  tests: false