name: Continuous integration workflow

on:
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: 1.23.3
  DATABASE_URL: postgres://user:password@localhost:5432/db?sslmode=disable
  GOOSE_MIGRATION_DIR: ./db/migrations

jobs:
  run-linters-to-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{env.GO_VERSION}}

    - name: Run linters
      uses: golangci/golangci-lint-action@v6.0.1
      with:
        version: latest

  check-sql-files:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: user
          POSTGRES_DB: db

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{env.GO_VERSION}}

    - name: Install Goose 
      run: go install -tags="no_clickhouse no_libsql no_mssql no_mysql no_sqlite3 no_vertica no_ydb" github.com/pressly/goose/v3/cmd/goose@latest

    - name: Create .env file
      run: echo -e "GOOSE_MIGRATION_DIR=${{env.GOOSE_MIGRATION_DIR}}\nDATABASE_URL=${{env.DATABASE_URL}}" > .env 

    - name: Set up migration
      run: make db-up

    - name: Validate migration schema files
      run: make db-check-migration-files

    - name: Install sqlc
      run: go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

    - name: Validate SQL queries
      run: make lint-queries

  audit-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{env.GO_VERSION}}

    - name: Download and verify dependencies
      run: go mod download & go mod verify

    - name: Check if the project compiles successfully
      run: make check-build

    - name: Run tests
      run: make test